services:
  web:
    image: php:8.3-apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "8094:80"
    command: >
      bash -lc "
        apt-get update &&
        DEBIAN_FRONTEND=noninteractive apt-get install -y \
          gcc make autoconf pkg-config \
          libtool tcl tcl-dev \
          expect \
          git wget unzip &&
        pecl install expect &&
        echo 'extension=expect.so' > /usr/local/etc/php/conf.d/expect.ini &&
        a2enmod rewrite &&
        sed -ri 's/AllowOverride\\s+None/AllowOverride All/i' /etc/apache2/apache2.conf &&
        apache2-foreground"
    networks: [labnet]

  meta:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - ./meta:/app
    command: python -u /app/server.py
    expose:
      - "8080"
    networks: [labnet]

networks:
  labnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
